Document: checksum
Title: Debian checksum Manual
Author: <insert document author here>
Abstract: This manual describes what checksum is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/checksum/checksum.sgml.gz

Format: postscript
Files: /usr/share/doc/checksum/checksum.ps.gz

Format: text
Files: /usr/share/doc/checksum/checksum.text.gz

Format: HTML
Index: /usr/share/doc/checksum/html/index.html
Files: /usr/share/doc/checksum/html/*.html
