#!/bin/bash

sha1out=`sha1sum $1`
sumArray=($sha1out)
inFileSum=${sumArray[0]}

if [ -n "$1" ]; then
	echo "Error: no file provided"
	exit 1
fi

if [ -n "$2" ]; then
	echo "Error: no sha1 checksum provided"
	exit 2
fi

if [[ "$inFileSum" == "$2" ]]; then
	echo ""
	echo ""
	echo -e "\e[1;34m  Provided Sum:\e[0m" $2
	echo -e "\e[1;34mCalculated Sum:\e[0m" $inFileSum
	echo ""
	echo -e "\e[1;32mHashes match. Download Successful.\e[0m"
	echo ""
	echo ""
else
	echo ""
	echo ""
	echo -e "\e[1;34m  Provided Sum:\e[0m" $2
	echo -e "\e[1;34mCalculated Sum:\e[0m" $inFileSum
	echo ""
	echo -e "\e[1;31mHashes do not match. Download corrupted.\e[0m"
	echo ""
	echo ""
fi
